# Libraries

In [2]:
import numpy as np
import scipy
from scipy import signal
import matplotlib.pyplot as plt
from pathlib import Path
import sys
import math

# root = str(Path().resolve().parent)
custom_pkg = str(Path().resolve().parent.parent / "python")
if custom_pkg not in sys.path:
    sys.path.append(custom_pkg)
print(*sys.path, sep="\n")

# %matplotlib ipympl
%matplotlib inline

/usr/lib/python312.zip
/usr/lib/python3.12
/usr/lib/python3.12/lib-dynload

/home/ryanwtsai/repos/rfdsp_sim/python/venv/lib/python3.12/site-packages
/home/ryanwtsai/repos/rfdsp_sim/python


In [3]:
from importlib import reload
from rfdsppy import calc, ofdm, rf_analog, rf_tx_fw, tonegen, digital_filter_design, digital_hw_algo as dighw

reload(calc)
reload(ofdm)
reload(rf_analog)
reload(rf_tx_fw)
reload(tonegen)
reload(digital_filter_design)
reload(dighw)

<module 'rfdsppy.digital_hw_algo' from '/home/ryanwtsai/repos/rfdsp_sim/python/rfdsppy/digital_hw_algo.py'>

# Polyphase Decomposition

In [4]:
# Prototype filter

M = 3
fp = 0.2
b = signal.firls(15, [0, fp, 2/M-fp, 1], [1, 1, 0, 0], fs=2)
b = b/b.sum()
b = np.round(b*(2**15-1))

print(b.astype("int"))

[  329   151  -816 -1597  -258  3956  8988 11262  8988  3956  -258 -1597
  -816   151   329]


In [5]:
# Polyphase components

e = []
for i in range(M):
    e.append(b[i::M])

print(*e, sep="\n")

[  329. -1597.  8988.  3956.  -816.]
[  151.  -258. 11262.  -258.   151.]
[ -816.  3956.  8988. -1597.   329.]


In [6]:
# Reconstruct prototype filter

e_up = []
for i in range(M):
    e_up.append(np.roll(np.concatenate((np.zeros(i), dighw.upsample(e[i], M))), i)[i:])

# print(*e_up, sep="\n")
print(np.array(e_up))

[[  329.     0.     0. -1597.     0.     0.  8988.     0.     0.  3956.
      0.     0.  -816.     0.     0.]
 [    0.   151.     0.     0.  -258.     0.     0. 11262.     0.     0.
   -258.     0.     0.   151.     0.]
 [    0.     0.  -816.     0.     0.  3956.     0.     0.  8988.     0.
      0. -1597.     0.     0.   329.]]


In [7]:
# Polyphase components

e = np.zeros((M, math.ceil(b.size/M)))
for i in range(M):
    e[i, :] = b[i::M]

print(e)

[[  329. -1597.  8988.  3956.  -816.]
 [  151.  -258. 11262.  -258.   151.]
 [ -816.  3956.  8988. -1597.   329.]]


In [8]:
# Upsample and shift polyphase components

e_up = np.zeros((M, e.shape[1]*M))
for i in range(M):
    e_up[i] = np.roll(np.concatenate((np.zeros(i), dighw.upsample(e[i], M))), i)[i:]

print(e_up)

# Reconstruct prototype filter

print(e_up.sum(axis=0))
print(e_up.sum(axis=0) - b)

[[  329.     0.     0. -1597.     0.     0.  8988.     0.     0.  3956.
      0.     0.  -816.     0.     0.]
 [    0.   151.     0.     0.  -258.     0.     0. 11262.     0.     0.
   -258.     0.     0.   151.     0.]
 [    0.     0.  -816.     0.     0.  3956.     0.     0.  8988.     0.
      0. -1597.     0.     0.   329.]]
[  329.   151.  -816. -1597.  -258.  3956.  8988. 11262.  8988.  3956.
  -258. -1597.  -816.   151.   329.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
b

array([  329.,   151.,  -816., -1597.,  -258.,  3956.,  8988., 11262.,
        8988.,  3956.,  -258., -1597.,  -816.,   151.,   329.])

In [10]:
e

array([[  329., -1597.,  8988.,  3956.,  -816.],
       [  151.,  -258., 11262.,  -258.,   151.],
       [ -816.,  3956.,  8988., -1597.,   329.]])

In [11]:
(e[0]+e[2])/2

array([-243.5, 1179.5, 8988. , 1179.5, -243.5])

In [12]:
(e[0]-e[2])/2

array([  572.5, -2776.5,     0. ,  2776.5,  -572.5])