In [1]:
import numpy as np
import scipy
import matplotlib.pyplot as plt

In [16]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a
a.shape
a.ndim
a.dtype.name
type(a.dtype)
a.dtype
a.itemsize
a.size
type(a)
b = np.array([6, 7, 8])
b
type(b)

numpy.ndarray

In [18]:
rg = np.random.default_rng(1)  # create instance of default random number generator
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *= 3
print(a)
b += a
print(b)
a += b  # b is not automatically converted to integer type

[[3 3 3]
 [3 3 3]]
[[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]]


UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [45]:
rng = np.random.default_rng()

In [55]:
a = rng.random((10))*2-1
print(a)
print(a.abs())

[-0.01064675 -0.28649645  0.42082874  0.2426568  -0.63637863  0.80650433
 -0.36198935 -0.11061737  0.79540468 -0.49497027]


AttributeError: 'numpy.ndarray' object has no attribute 'abs'

In [49]:
print(*dir(rng.random((10)).mean()), sep="\n")

T
__abs__
__add__
__and__
__array__
__array_interface__
__array_namespace__
__array_priority__
__array_struct__
__array_wrap__
__bool__
__buffer__
__ceil__
__class__
__class_getitem__
__copy__
__deepcopy__
__delattr__
__dir__
__divmod__
__doc__
__eq__
__float__
__floor__
__floordiv__
__format__
__ge__
__getattribute__
__getformat__
__getitem__
__getnewargs__
__getstate__
__gt__
__hash__
__init__
__init_subclass__
__int__
__invert__
__le__
__lshift__
__lt__
__mod__
__mul__
__ne__
__neg__
__new__
__or__
__pos__
__pow__
__radd__
__rand__
__rdivmod__
__reduce__
__reduce_ex__
__repr__
__rfloordiv__
__rlshift__
__rmod__
__rmul__
__ror__
__round__
__rpow__
__rrshift__
__rshift__
__rsub__
__rtruediv__
__rxor__
__setattr__
__setstate__
__sizeof__
__str__
__sub__
__subclasshook__
__truediv__
__trunc__
__xor__
all
any
argmax
argmin
argsort
as_integer_ratio
astype
base
byteswap
choose
clip
compress
conj
conjugate
copy
cumprod
cumsum
data
device
diagonal
dtype
dump
dumps
fill
flags
flat
flatten
fro

In [44]:
np.empty(0)

array([], dtype=float64)

In [61]:
import numpy as np
from scipy import signal

def psd(x: np.ndarray, fs, rbw, wintype='kaiser', **kwargs):
    """
    Calculate PSD of a signal
    
    Parameters
    ----------
    x : signal in Volts
    fs : sampling rate in MHz
    rbw : desired resolution BW in MHz
    wintype : determines type of window to use on each segment

    Returns
    -------
    p : PSD of x in V^2/Hz
    f : PSD frequencies in MHz
    
    """
    
    nfft = np.ceil(fs/rbw)

    print(kwargs)
    
    if wintype == 'kaiser':
        # taps = signal.windows.kaiser(nfft,25)
        taps = signal.windows.kaiser(nfft, **kwargs)
        print(taps)

In [64]:
taps = signal.windows.kaiser(20, beta=25)
taps

array([1.73173349e-10, 1.47706224e-06, 8.20643667e-05, 1.34940813e-03,
       1.09695631e-02, 5.40200287e-02, 1.78769108e-01, 4.21874155e-01,
       7.35486335e-01, 9.66620479e-01, 9.66620479e-01, 7.35486335e-01,
       4.21874155e-01, 1.78769108e-01, 5.40200287e-02, 1.09695631e-02,
       1.34940813e-03, 8.20643667e-05, 1.47706224e-06, 1.73173349e-10])

In [62]:
x = np.arange(15)
fs = 20
rbw = 1

psd(x, fs, rbw, beta=25)

{'beta': 25}
[1.73173349e-10 1.47706224e-06 8.20643667e-05 1.34940813e-03
 1.09695631e-02 5.40200287e-02 1.78769108e-01 4.21874155e-01
 7.35486335e-01 9.66620479e-01 9.66620479e-01 7.35486335e-01
 4.21874155e-01 1.78769108e-01 5.40200287e-02 1.09695631e-02
 1.34940813e-03 8.20643667e-05 1.47706224e-06 1.73173349e-10]


In [65]:
a = [0, 1]
b, c = a
print(b)
print(c)

0
1


In [71]:
x = np.arange(10) + 1j*np.arange(10)
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
(x*x.conj()).real.sum()

np.int64(285)

In [74]:
np.vdot(x, x)

np.int64(285)