In [1]:
import numpy as np
import scipy
import matplotlib.pyplot as plt

In [16]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a
a.shape
a.ndim
a.dtype.name
type(a.dtype)
a.dtype
a.itemsize
a.size
type(a)
b = np.array([6, 7, 8])
b
type(b)

numpy.ndarray

In [18]:
rg = np.random.default_rng(1)  # create instance of default random number generator
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *= 3
print(a)
b += a
print(b)
a += b  # b is not automatically converted to integer type

[[3 3 3]
 [3 3 3]]
[[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]]


UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [24]:
type(np.maximum)
type(np.max)

numpy._ArrayFunctionDispatcher

In [28]:
a = np.ones((2,5))
b = np.ones((5,2))

np.dot(a,b)

array([[5., 5.],
       [5., 5.]])

In [33]:
np.prod(np.arange(1,5))
np.cumprod(np.arange(1,5))

array([ 1,  2,  6, 24])

In [37]:
a = np.ones((3,4,5))
np.transpose(a).shape

(5, 4, 3)

In [42]:
np.empty((2,2))

array([[4.9e-324, 9.9e-324],
       [1.5e-323, 2.0e-323]])